POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmOWI5Mjg3YTIwOTI4MmQwNGFhNWI5NSIsImlhdCI6MTYwNDExNjA1N30.DPwDuGsdSIkn1TlOOPzZt9JJ1wbToTqqrU3AnP7cLo0

{
  "title": "Blog created with token auth",
  "author": "jwt",
  "url": "jwt.net",
  "likes": 10
}

// root token